name: SonarCloud
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  info:
    name: PR Info
    runs-on: ubuntu-latest
      steps:
      - run: |
          echo GITHUB PULL REQUEST NUMBER ${{ github.event.pull_request.number }} nd EVENT ISSUE NUMBER ${{ github.event.issue.number }}
          echo GITHUB SHA ${{github.event.pull_request.head.sha }}
