name: OnComment
on: 
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }} && ${{ github.event.comment.body == 'run'}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo GITHUB PULL REQUEST NUMBER ${{ github.event.issue.pull_request.number }} nd EVENT ISSUE NUMBER ${{ github.event.issue.number }}
        env:
          NUMBER: ${{ github.event.issue.number }}
